CREATE DATABASE MERCADO

USE MERCADO

CREATE TABLE CLIENTE(
ID INT IDENTITY (1,1) PRIMARY KEY,
NOME VARCHAR(30) NOT NULL,
CPF VARCHAR(12) NOT NULL UNIQUE,
DATA_CADASTRO DATE NOT NULL DEFAULT GETDATE()
)

CREATE TABLE PRODUTO(
ID INT IDENTITY (1,1) PRIMARY KEY,
NOME VARCHAR(30) NOT NULL,
PRECO MONEY
)

CREATE TABLE VENDA(
ID INT IDENTITY (1,1) PRIMARY KEY,
ID_CLIENTE INT,
ID_PRODUTO INT,
DATA_VENDA DATE DEFAULT GETDATE(),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID),
FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID)
)

INSERT CLIENTE (NOME, CPF)
	VALUES
	('KAIKY','144289499-79'),
	('BRUNO','123456789-69'),
	('PETER','987654321-69')

INSERT PRODUTO
	VALUES
	('CHAVE DE FENDA', 19.99),
	('CHAVE PHILLIPS MEGA BLASTER', 25.50),
	('MARTELO O MARTELÃO', 200.00),
	('SERRA ELETRYKA',189.90),
	('PETERSON',0.0)

INSERT VENDA (ID_CLIENTE, ID_PRODUTO)
	VALUES
	(1,5),
	(2,2),
	(3,4),
	(1,3),
	(2,1),
	(3,5)

SELECT * FROM CLIENTE 
SELECT * FROM PRODUTO
SELECT * FROM VENDA

SELECT * FROM VENDA V --TUDO
JOIN CLIENTE C ON V.ID_CLIENTE = C.ID
JOIN PRODUTO P ON V.ID_PRODUTO = P.ID

SELECT C.NOME AS Clientes, P.NOME AS Produtos, P.PRECO AS 'Valor Pago' FROM VENDA V --CLIENTE, PRODUTO E PREÇO
JOIN CLIENTE C ON V.ID_CLIENTE = C.ID
JOIN PRODUTO P ON V.ID_PRODUTO = P.ID

SELECT C.NOME AS Clientes, SUM(P.PRECO) AS 'Valor Total' FROM VENDA V -- CLIENTE E VALOR PAGO NO TOTAL DAS COMPRAS
JOIN CLIENTE C ON V.ID_CLIENTE = C.ID
JOIN PRODUTO P ON V.ID_PRODUTO = P.ID
GROUP BY C.NOME


