CREATE TABLE PALESTRAS(
ID INT IDENTITY(1,1) PRIMARY KEY,
NOME VARCHAR(30)
)

CREATE TABLE OFICINAS(
ID INT IDENTITY(1,1) PRIMARY KEY,
NOME VARCHAR(30)
)

CREATE TABLE FORUNS(
ID INT IDENTITY(1,1) PRIMARY KEY,
NOME VARCHAR(30)
)

CREATE TABLE INSCRITOS(
ID INT IDENTITY(1,1) PRIMARY KEY,
NOME VARCHAR(30),
ID_PALESTRA INT,
ID_OFICINA INT,
ID_FORUM INT,
FOREIGN KEY (ID_PALESTRA) REFERENCES PALESTRAS(ID),
FOREIGN KEY (ID_OFICINA) REFERENCES OFICINAS(ID),
FOREIGN KEY (ID_FORUM) REFERENCES FORUNS(ID)
)

CREATE TABLE INSPETOR(
ID INT IDENTITY (1,1), 
ID_PALESTRA INT
)

ALTER TABLE INSPETOR
ADD CONSTRAINT PK_INSPETOR PRIMARY KEY(ID)

ALTER TABLE INSPETOR
ADD CONSTRAINT FK_INSPETOR FOREIGN KEY(ID_PALESTRA) REFERENCES PALESTRAS(ID)

INSERT PALESTRAS VALUES('LEARN MACHINE')
INSERT OFICINAS VALUES('DESENV. MOBILE')
INSERT FORUNS VALUES ('O MERCADO DE CIENCIA DE DADOS')

INSERT INSCRITOS VALUES ('MARCELO', 1,1,1)
